name: music
description: Music app with local library scanner and player
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  just_audio: ^0.10.05
  audio_service: ^0.18.15
  permission_handler: ^12.0.1
  shared_preferences: ^2.3.2
  path_provider: ^2.1.5
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
